language: java

cache:
  directories:
    - $HOME/.m2

install:
  - java -XX:+PrintFlagsFinal -version
  - mvn --version

script: mvn verify animal-sniffer:check --update-snapshots --settings .travis.settings.xml -e

jdk: openjdk8
